var H1 = document.getElementById("H_1")
var H2 = document.getElementById("H_2")

var P1 = document.getElementById("P_1")
var P2 = document.getElementById("P_2")

var H3 = document.getElementById("H_3")
var H4 = document.getElementById("H_4")

var H5 = document.getElementById("H_5")
var H6 = document.getElementById("H_6")

var V1 = document.getElementById("V_1")
var V2 = document.getElementById("V_2")

var F1 = document.getElementById("F1")
var F2 = document.getElementById("F2")

var IM1 = document.getElementById("Image1")
var IM2 = document.getElementById("Image2")

var IM = document.getElementById("Image_id")
function H1_S() {

  H2.style.display = "none"
  H1.style.display = "block"
  
  P2.style.display = "none"
  P1.style.display = "block"

  H4.style.display = "none"
  H3.style.display = "block"

  H6.style.display = "none"
  H5.style.display = "block"

  V2.style.display = "none"
  V1.style.display = "block"

  
  IM2.style.display = "none"
  IM1.style.display = "block"
  
  F2.style.display = "none"
  F1.style.display = "block"
}

function H2_S() {
    
    H1.style.display = "none"
    H2.style.display = "block"
    
    P1.style.display = "none"
    P2.style.display = "block"

    H3.style.display = "none"
    H4.style.display = "block"

    H5.style.display = "none"
    H6.style.display = "block"

    V2.style.display = "block"
    V1.style.display = "none"

    IM1.style.display = "none"
    IM2.style.display = "block"

    F1.style.display = "none"
    F2.style.display = "block"

}


